### ISSUE TITLE
Tests failing on beanstalkd master branch

### ISSUE THREAD

**Issue by SamMousa** [justinmayhew/greenstalk#9]
Hey, I've been working on a PR to run test suites of beanstalkd clients on pushes to the beanstalkd source code.
(The PR is not yet merged: https://github.com/beanstalkd/beanstalkd/pull/614)

I'm posting this here since greenstalk tests will fail as soon as a new beanstalkd version is released:

https://github.com/SamMousa/beanstalkd/runs/4712188954?check_suite_focus=true

**Comment by justinmayhew** [comment]
Hi there, I think you meant to link to [this](https://github.com/SamMousa/beanstalkd/runs/4712191966?check_suite_focus=true).

It looks like the tube name now has double quotes surrounding it. The "YAML" parser in this library is super naive so it's not a surprise that something eventually broke.

Thanks for opening this issue.

**Comment by SamMousa** [comment]
> It looks like the tube name now has double quotes surrounding it. 

Yeah it's definitely that, that's the change I authored that got merged.

**Comment by justinmayhew** [comment]
Fixed in commit 5f4f42438d102037102da4f1e1c207617cc4ed41.
